### ISSUE TITLE
Bug when jumping to a platform; you can hover beneath the platform.

### ISSUE THREAD

**Issue by Tarovk** [lkroesen/BubbleBobble#10]
The game is kind of buggy when jumping to a platform. You can hover beneath the platform. If you jump again, you will end up on the platform.

This is most likely caused by the fact that a platform is currently treated as a full cell in height.

**Comment by LarsStegman** [comment]
I think it's because the Unit detects the collision and sets its y speed to 0. It should move to the top of the cell before changing its y speed. Not treating the platform as a full height cell, will cause the unit to be able to move trough it when running into it from the side, but we can look into it.

**Comment by LarsStegman** [comment]
I just experienced this bug, it's still present unfortunately.

**Comment by 8uurg** [comment]
#24 fixes this issue.
